# Generated by Django 3.2.7 on 2021-10-20 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
